# Get all users.
// @no-cookie-jar
GET http://localhost:9080/jakarta-ee-project/api/users
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User

###

# Get single user.
// @no-cookie-jar
GET http://localhost:9080/jakarta-ee-project/api/users/ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User

###

# Delete single user.
// @no-cookie-jar
DELETE http://localhost:9080/jakarta-ee-project/api/users/ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User

###

# Put single user.
// @no-cookie-jar
PUT http://localhost:9080/jakarta-ee-project/api/users/ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197
Content-Type: application/json

{
  "login": "maniek",
  "name": "Maciek",
  "email" : "maciek@gmail.com",
  "password": "maciek123"
}

###

# Patch single user.
// @no-cookie-jar
PATCH http://localhost:9080/jakarta-ee-project/api/users/ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
Content-Type: application/json

{
  "login": "maciek11111",
  "name": "Maciek1111",
  "email" : "maciek1111@gmail.com"
}


###

# Create user avatar.
// @no-cookie-jar
PUT http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar1.png"

< C:\Users\franc\Desktop\SEMESTR 7\jakarta-ee-project\src\main\resources\pl.edu.pg.eti.kask.app.configuration.avatar/avatar1.png
--boundary--

###

# Patch user avatar.
// @no-cookie-jar
PATCH http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar2.png"

< C:\Users\franc\Desktop\SEMESTR 7\jakarta-ee-project\src\main\resources\pl.edu.pg.eti.kask.app.configuration.avatar/avatar2.png
--boundary--

###

# Get single user avatar.
// @no-cookie-jar
GET http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar

###

# Delete single user avatar.
// @no-cookie-jar
DELETE http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar

###

# Get all categories.
// @no-cookie-jar
GET http://localhost:9080/jakarta-ee-project/api/categories
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
###

# Get single category.
// @no-cookie-jar
GET http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
#Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
###

# Delete single category.
// @no-cookie-jar
DELETE http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
###

# Put single category.
// @no-cookie-jar
PUT http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
Content-Type: application/json

{
  "name": "Breakfast",
  "description": "Breakfast"
}

###

# Patch single category.
// @no-cookie-jar
PATCH http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
Content-Type: application/json

{
  "name": "Sweet breakfast",
  "description": "Sweet breakfast"
}

###

# Get all recipes.
// @no-cookie-jar
GET http://localhost:9080/jakarta-ee-project/api/recipes
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
###

# Get single recipe.
// @no-cookie-jar
GET http://localhost:9080/jakarta-ee-project/api/categories/5d1da2ae-6a14-4b6d-8b4f-d117867118d4/recipes/e08ef7e3-7f2a-4378-b1fb-2922d730c70d
#Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
###

# Delete single recipe.
// @no-cookie-jar
DELETE http://localhost:9080/jakarta-ee-project/api/categories/5d1da2ae-6a14-4b6d-8b4f-d117867118d4/recipes/e08ef7e3-7f2a-4378-b1fb-2922d730c70d
#Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
###

# Put single recipe.
// @no-cookie-jar
PUT http://localhost:9080/jakarta-ee-project/api/categories/5d1da2ae-6a14-4b6d-8b4f-d117867118d4/recipes/e08ef7e3-7f2a-4378-b1fb-2922d730c70d
#Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
Content-Type: application/json

{
  "name": "Spaghetti",
  "description": "Spaghetti",
  "difficulty" : "Medium"
}

###

# Patch single recipe.
// @no-cookie-jar
PATCH http://localhost:9080/jakarta-ee-project/api/categories/5d1da2ae-6a14-4b6d-8b4f-d117867118d4/recipes/e08ef7e3-7f2a-4378-b1fb-2922d730c70d
#Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
Content-Type: application/json

{
  "name": "Spaghetti carbonara",
  "description": "Spaghetti carbonara",
  "difficulty" : "Hard"
}

###

# Get all category's recipes.
// @no-cookie-jar
GET http://localhost:9080/jakarta-ee-project/api/categories/5d1da2ae-6a14-4b6d-8b4f-d117867118d4/recipes
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
###

# Get all user's recipes.
// @no-cookie-jar
GET http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/recipes
Authorization: Basic YWRtaW46YWRtaW4xMjM= #Admin
#Authorization: Basic ZnJhbmVrNzM6ZnJhbmVrMTIz #User
###