# Get all users.

GET http://localhost:9080/jakarta-ee-project/api/users

###

# Get single user.

GET http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e

###

# Delete single user.

DELETE http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e

###

# Put single user.

PUT http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e
Content-Type: application/json

{
  "login": "franek73",
  "name": "Franek",
  "email" : "franek@gmail.com",
  "password": "franek123"
}

###

# Patch single user.

PATCH http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e
Content-Type: application/json

{
  "login": "franek",
  "name": "Franek",
  "email" : "franek73@gmail.com"
}

###

# Create user avatar.

PUT http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar1.png"

< C:\Users\franc\Desktop\SEMESTR 7\jakarta-ee-project\src\main\resources\pl.edu.pg.eti.kask.app.configuration.avatar/avatar1.png
--boundary--

###

# Patch user avatar.

PATCH http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar2.png"

< C:\Users\franc\Desktop\SEMESTR 7\jakarta-ee-project\src\main\resources\pl.edu.pg.eti.kask.app.configuration.avatar/avatar2.png
--boundary--

###

# Get single user avatar.

GET http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar

###

# Delete single user avatar.

DELETE http://localhost:9080/jakarta-ee-project/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar

###

# Get all categories.

GET http://localhost:9080/jakarta-ee-project/api/categories

###

# Get single category.

GET http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

###

# Delete single category.

DELETE http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

###

# Put single category.

PUT http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Content-Type: application/json

{
  "name": "Breakfast",
  "description": "Breakfast"
}

###

# Patch single category.

PATCH http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Content-Type: application/json

{
  "name": "Sweet breakfast",
  "description": "Sweet breakfast"
}

###

# Get all recipes.

GET http://localhost:9080/jakarta-ee-project/api/recipes

###

# Get single recipe.

GET http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/recipes/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0

###

# Delete single recipe.

DELETE http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/recipes/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0

###

# Put single recipe.

PUT http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/recipes/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0
Content-Type: application/json

{
  "name": "Porridge",
  "description": "Porridge",
  "difficulty" : "Easy"
}

###

# Patch single recipe.

PATCH http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/recipes/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0
Content-Type: application/json

{
  "name": "Porridge with raspberries",
  "description": "Porridge with raspberries",
  "difficulty" : "Medium"
}

###

# Get all category's recipes.

GET http://localhost:9080/jakarta-ee-project/api/categories/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/recipes

###

# Get all user's recipes.

GET http://localhost:9080/jakarta-ee-project/api/users/ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197/recipes

###